const express = require("express")
const {UserModel} = require("../models/usermodel")

const userRouter = express.Router()

// Register Users

// YAML
/**
 * @swagger
 * components:
 *   schemas:
 *     User:
 *       type: object
 *       properties:
 *         id:
 *           type: string
 *           description: The unique ID generated by MongoDB.
 *         username:
 *           type: string
 *           description: The username of the user.
 *         email:
 *           type: string
 *           description: The email of the user.
 *         password:
 *           type: string
 *           description: The password of the user.
 */

/**
 * @swagger
 *  tags:
 *      name: Users
 *      description: All the API routes to users.
 */

/**
 * @swagger
 *  /users/register:
 *      post:
 *          summary: Register a new user.
 *          tags: [Users]
 *          requestBody:
 *              required: true
 *              content: 
 *                  application/json:
 *                      schema:
 *                          $ref: "#/components/schemas/User"
 *          responses:
 *              '200':
 *                  description: The user has been registered successfully.
 *              '400':
 *                  description: Something went Wrong
 */

userRouter.post("/register", async(req, res)=>{
    const {username, email, password} = req.body
    try {
        const user = new UserModel({username, email, password})
        await user.save()
        res.status(200).send({"msg":"Registration Successful"})
    } catch (error) {
        res.status(400).send({"msg":"some thing went wrong while registering"})
    }
})

// Login User

/**
 * @swagger
 *  /users/login:
 *      post:
 *          summary: Login a new user.
 *          tags: [Users]
 *          requestBody:
 *              required: true
 *              content: 
 *                  application/json:
 *                      schema:
 *                          type: object
 *                          properties:
 *                              email:
 *                                  type: string
 *                                  description: Users Email
 *                              password:
 *                                  type: string
 *                                  description: Users Password
 * 
 *          responses:
 *              '200':
 *                  description: The user has been Login successfully.
 *              '400':
 *                  description: Something went Wrong
 */

userRouter.post("/login", async(req, res)=>{
    const {email, password} = req.body
    try {
        const user = await UserModel.findOne({email, password})
        res.status(200).send({"msg":"Login Successful"})
    } catch (error) {
        res.status(400).send({"Error":error})
    }
})

module.exports = {userRouter}